name: Prod - Deploy APP backend API to FTP 

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package
        working-directory: ./jo

      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTPSERVERPROD }}
          username: ${{ secrets.FTPUSERNAMEPROD }}
          password: ${{ secrets.FTPPASSWORDPROD }}
          local-dir: ./jo/target  # Répertoire contenant le fichier JAR généré par Maven
          server-dir: /www/api/
